services:
  postgre:
    image: postgres:13.13
    ports:
      - 5432:5243
    environment:
      POSTGRES_PASSWORD: kube
      POSTGRES_USER: kubenewsadm
      POSTGRES_DB: kubenews
  kubenews:
    image: victordev13/kube-news:1.0.2
    # descomentar para usar o build local
    # build:
    #   context: ./src
    #   dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenewsadm
      DB_PASSWORD: kube
      DB_HOST: postgre
    depends_on:
      - postgre

networks:
 kubenews:
  driver: bridge
